service: viva-api

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  stage: ${opt:stage, self:provider.stage}
  resourcesStages:
    prod: prod
    dev: dev
  resourcesStage: ${self:custom.resourcesStages.${self:custom.stage}, self:custom.resourcesStages.dev}
  pythonRequirements:
    vendor: ./libs
    invalidateCaches: true
    dockerizePip: false
    zip: true
    slim: true

package:
  individually: true

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-north-1
  endpointType: regional
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:DescribeParameters
      Resource: "*"

functions:
  example:
    handler: example.hello
    events:
      - http:
          path: example
          method: get
          cors: true
  getApplication:
    handler: lambdas/application/get.main
    events:
      - http:
          path: viva/application/{personNumber}/{id}
          method: get
          cors: true
  listApplications:
    handler: lambdas/application/list.main
    events:
      - http:
          path: viva/application/{personNumber}
          method: get
          cors: true
  createApplication:
    handler: lambdas/application/create.main
    events:
      - http:
          path: viva/application/{personNumber}
          method: post
          cors: true
