service: viva-api

plugins:
  - serverless-offline
  - serverless-python-requirements

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-north-1
  endpointType: regional
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "*"

functions:
  example:
    handler: example.hello
    events:
      - http:
          path: example
          method: get
          cors: true
