service: viva-ms

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-s3-remover

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  tracing:
    apiGateway: false
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - SSM:GetParameter
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:ListStreams
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:Query
      # Restrict our IAM role permissions to the specific table for the stage
      Resource:
        - "Fn::ImportValue": ${self:custom.resourcesStage}-CasesTableArn

functions:
  submitApplication:
    handler: lambdas/submitApplication.main
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::ImportValue: ${self:custom.resourcesStage}-CasesTableStreamArn

  syncOfficers:
    handler: lambdas/syncOfficers.main
    events:
      - eventBridge:
          pattern:
            source:
              - cases.database
            detail-type:
              - INSERT
              - MODIFY
            detail:
              dynamodb:
                NewImage:
                  provider:
                    S: ["VIVA"]

  createVivaCase:
    handler: lambdas/createVivaCase.main
    events:
      - eventBridge:
          pattern:
            source:
              - bankId.collect
            detail-type:
              - BankIdCollectComplete

  syncWorkflow:
    handler: lambdas/syncWorkflow.main
    events:
      - eventBridge:
          pattern:
            source:
              - cases.database
            detail-type:
              - MODIFY
            detail:
              dynamodb:
                NewImage:
                  status:
                    M:
                      type:
                        S:
                          [
                            { "prefix": "active:submitted" },
                            { "prefix": "active:ongoing" },
                          ]
