service: viva-ms

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-s3-remover

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  tracing:
    apiGateway: false
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - SSM:GetParameter
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:ListStreams
        - dynamodb:UpdateItem
      # Restrict our IAM role permissions to the specific table for the stage
      Resource:
        - "Fn::ImportValue": ${self:custom.resourcesStage}-CasesTableArn

functions:
  submitApplication:
    handler: lambdas/submitApplication.main
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::ImportValue: ${self:custom.resourcesStage}-CasesTableStreamArn

  syncOfficers:
    handler: lambdas/syncOfficers.main
    events:
      - eventBridge:
          pattern:
            source:
              - cases.database
            detail-type:
              - INSERT
              - MODIFY
            detail:
              dynamodb:
                NewImage:
                  provider:
                    S: ["VIVA"]

  syncApplicationStatus:
    handler: lambdas/syncApplicationStatus.main
    events:
      - eventBridge:
          pattern:
            source:
              - bankId.collectMockApplicationStatus
            detail-type:
              - BankIdCollectComplete

  syncPeriod:
    handler: lambdas/syncPeriod.main
    events:
      - eventBridge:
          pattern:
            source:
              - bankId.collectMockPeriod
            detail-type:
              - BankIdCollectComplete

  # syncWorkflow:
  #   handler: lambdas/syncWorkflow.main
  #   events:
  #     - eventBridge:
  #         pattern:
  #           source:
  #             - bankId.collectMock
  #           detail-type:
  #             - BankIdCollectComplete
