service: viva-ms

plugins:
  - serverless-bundle

projectDir: ../../

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  eventBridge:
    useCloudFormation: true
  tracing:
    apiGateway: false
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - SSM:GetParameter*
          Resource:
            - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${file(../../config.json):${self:custom.stage}.vada.envsKeyName}'
            - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${file(../../config.json):${self:custom.stage}.cases.providers.viva.envsKeyName}'

        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: '*'

        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource:
            - Fn::ImportValue: ${self:custom.resourcesStage}-AttachmentsBucketArn
            - Fn::Join:
                - ''
                - - Fn::ImportValue: ${self:custom.resourcesStage}-AttachmentsBucketArn
                  - '/*'
            - Fn::ImportValue: ${self:custom.resourcesStage}-PdfStorageBucketArn
            - Fn::Join:
                - ''
                - - Fn::ImportValue: ${self:custom.resourcesStage}-PdfStorageBucketArn
                  - '/*'

        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:GetItem
          Resource:
            - 'Fn::ImportValue': ${self:custom.resourcesStage}-CasesTableArn

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
          Resource:
            - 'Fn::ImportValue': ${self:custom.resourcesStage}-UsersTableArn

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
          Resource:
            - 'Fn::ImportValue': ${self:custom.resourcesStage}-FormsTableArn

        - Effect: Allow
          Action:
            - kms:Decrypt
            - kms:GenerateDataKey
          Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*

functions:
  applicationStatus:
    handler: src/lambdas/applicationStatus.main
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - usersMs.findUser
            detail-type:
              - usersMsFindUserSuccess
      - eventBridge:
          pattern:
            source:
              - vivaMs.submitApplication
            detail-type:
              - applicationReceivedSuccess

  personApplicationStatus:
    handler: src/lambdas/personApplicationStatus.main
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.applicationStatus
            detail-type:
              - applicationStatusSuccess

  personApplication:
    handler: src/lambdas/personApplication.main
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.personApplicationStatus
            detail-type:
              - checkOpenPeriodSuccess

  createVivaCase:
    handler: src/lambdas/createVivaCase.main
    reservedConcurrency: 1
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.personApplication
            detail-type:
              - personDetailSuccess

  submitApplication:
    handler: src/lambdas/submitApplication.main
    timeout: 15
    events:
      - sqs:
          arn: !ImportValue ${self:custom.stage}-VivaSubmissionQueueArn
          batchSize: 1

  syncCaseCompletions:
    handler: src/lambdas/syncCaseCompletions.main
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.applicationStatus
            detail-type:
              - applicationStatusSuccess

  checkCompletionsStatus:
    handler: src/lambdas/checkCompletionsStatus.main
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.syncCaseCompletions
            detail-type:
              - syncSuccess

  setCaseCompletions:
    handler: src/lambdas/setCaseCompletions.main
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.checkCompletionsStatus
            detail-type:
              - checkCompletionsStatusRequired
            detail:
              caseStatusType: [{ 'anything-but': { 'prefix': 'active:ongoing' } }]
              caseState:
                [
                  { 'anything-but': 'VIVA_RANDOM_CHECK_RECEIVED' },
                  { 'anything-but': 'VIVA_COMPLETION_RECEIVED' },
                ]

  checkCompletionsDueDate:
    handler: src/lambdas/checkCompletionsDueDate.main
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.checkCompletionsStatus
            detail-type:
              - 'Completions Due Date Probably Overdue'
            detail:
              caseStatusType: [{ 'anything-but': { 'prefix': 'active:processing' } }]

  submitCompletion:
    handler: src/lambdas/submitCompletion.main
    timeout: 15
    environment:
      BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-AttachmentsBucketName
    events:
      - eventBridge:
          pattern:
            source:
              - casesApi.updateCase
            detail-type:
              - casesApiUpdateCaseSuccess
            detail:
              status:
                type: [{ 'prefix': 'active:submitted' }]
              state: ['VIVA_RANDOM_CHECK_REQUIRED', 'VIVA_COMPLETION_REQUIRED']

  syncOfficers:
    handler: src/lambdas/syncOfficers.main
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - cases.database
            detail-type:
              - INSERT
              - MODIFY
            detail:
              dynamodb:
                NewImage:
                  provider:
                    S: ['VIVA']

  syncWorkflow:
    handler: src/lambdas/syncWorkflow.main
    timeout: 15
    events:
      - eventBridge:
          pattern:
            source:
              - bankId.collect
            detail-type:
              - BankIdCollectComplete

  decideCaseStatus:
    handler: src/lambdas/decideCaseStatus.main
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.syncWorkflow
            detail-type:
              - syncWorkflowSuccess

  syncExpiryTime:
    handler: src/lambdas/syncExpiryTime.main
    events:
      - eventBridge:
          pattern:
            source:
              - casesApi.updateCase
      - eventBridge:
          pattern:
            source:
              - vivaMs.decideCaseStatus
      - eventBridge:
          pattern:
            source:
              - vivaMs.setCaseCompletions

  generateRecurringCaseHtml:
    handler: src/lambdas/generateRecurringCaseHtml.main
    environment:
      PDF_STORAGE_BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-PdfStorageBucketName
    events:
      - eventBridge:
          pattern:
            source:
              - casesApi.updateCase
            detail-type:
              - casesApiUpdateCaseSuccess
            detail:
              status:
                type: [{ 'prefix': 'active:submitted' }]
              state: ['VIVA_CASE_CREATED']
