service: helsingborg-io-sls-forminput-api

plugins:
  - serverless-bundle
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  tracing:
    apiGateway: true
    lambda: true

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /forms
  # - method: POST request
  create:
    handler: create.main
    events:
      - http:
          path: api/v1/forms
          method: post
          cors: true
  list:
    handler: list.main
    events:
      - http:
          path: api/v1/forms
          method: get
          cors: true
