service: helsingborg-io-sls-forminput-api

plugins:
  - serverless-bundle
  - serverless-offline

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  tracing:
    apiGateway: true
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to the specific table for the stage
      Resource:
        - 'Fn::ImportValue': ${self:custom.resourcesStage}-SubmissionsTableArn

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /forms
  # - method: POST request
  create:
    handler: create.main
    events:
      - http:
          path: api/v1/forms
          method: post
          cors: true
          authorizer: aws_iam

  list:
    handler: list.main
    events:
      - http:
          path: api/v1/forms
          method: get
          cors: true
          authorizer: aws_iam
