service: helsingborg-io-sls-forminput-api

plugins:
  - serverless-bundle
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  tracing:
    apiGateway: true
    lambda: true
