service: hbg-forms

plugins:
  - serverless-bundle
  - serverless-offline

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}
  apiGateway:
    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
    restApiResources:
      forms:
        "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayResourceForms

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem

      Resource:
        - "Fn::ImportValue": ${self:custom.resourcesStage}-FormsTableArn

functions:
  getForm:
    handler: lambdas/getForm.main
    events:
      - http:
          path: /forms/{formId}
          method: get
          cors: true

  createForms:
    handler: lambdas/createForms.main
    events:
      - http:
          path: /forms
          method: post
          cors: true

  addFormSteps:
    handler: lambdas/addFormSteps.main
    events:
      - http:
          path: /forms/{formId}/steps
          method: post
          cors: true

  addFormFields:
    handler: lambdas/addFormQuestions.main
    events:
      - http:
          path: /forms/{formId}/steps/{stepId}/questions
          method: post
          cors: true

  addFormLogics:
    handler: lambdas/addFormLogics.main
    events:
      - http:
          path: /forms/{formId}/logics
          method: post
          cors: true
