service: bankid-api

plugins:
  - serverless-bundle

projectDir: ../../

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  tracing:
    lambda: true
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
    restApiResources:
      auth:
        'Fn::ImportValue': ${self:custom.stage}-ExtApiGatewayResourceAuth

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:getObject
          Resource:
            - 'Fn::Join':
                - ''
                - - Fn::ImportValue: ${self:custom.stage}-CertificatesBucketArn
                  - '/*'
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: '*'

        - Effect: Allow
          Action:
            - SSM:GetParameter*
          Resource:
            - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${file(../../config.json):${self:custom.stage}.bankId.envsKeyName}'
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${file(../../config.json):${self:custom.stage}.auth.secrets.accessToken.name}-??????'
            - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${file(../../config.json):${self:custom.stage}.auth.secrets.refreshToken.name}-??????'
            - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${file(../../config.json):${self:custom.stage}.auth.secrets.authorizationCode.name}-??????'

        - Effect: Allow
          Action:
            - kms:Decrypt
          Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*
functions:
  auth:
    handler: src/lambdas/auth.main
    events:
      - http:
          path: auth/bankid/auth
          method: post
          private: true
          cors: true
  sign:
    handler: src/lambdas/sign.main
    events:
      - http:
          path: auth/bankid/sign
          method: post
          private: true
          cors: true
  collect:
    handler: src/lambdas/collect.main
    events:
      - http:
          path: auth/bankid/collect
          method: post
          private: true
          cors: true
  cancel:
    handler: src/lambdas/cancel.main
    events:
      - http:
          path: auth/bankid/cancel
          method: post
          private: true
          cors: true
