openapi: '3.0.3'
info:
  title: Users api
  description: Api dealing with users and their uploaded attachments.
  contact:
    name: GitHub Repo
    url: https://github.com/helsingborg-stad/helsingborg-io-sls-api
  version: '1.0'
  license:
    name: MIT
    url: 'https://github.com/helsingborg-stad/helsingborg-io-sls-api#license'
servers:
  - url: https://dev.api.helsingborg.io
  - url: https://release.api.helsingborg.io
  - url: https://api.helsingborg.io

paths:
  /users/me:
    get:
      tags:
        - User
      summary: Fetch user.
      description: This endpoint returns an object containing user data.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            format: JWT
          required: true
      responses:
        '200':
          description: OK.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetUserResponse'
        '401':
          description: Invalid JWT.
          content:
            'application/json':
              schema:
                $ref: '../common-openapi.yml#/components/schemas/jsonApiError'
        '403':
          $ref: '../common-openapi.yml#/components/responses/missingApiKeyResponse'

  /users/me/attachments:
    get:
      tags:
        - Attachments
      summary: Fetch list of attachments.
      description: |
        This endpoints returns a lists of attachments that exists under a specific key in S3.

        Note that this endpoint doesn't return the objects themselves in the response, only 
        the metadata, like key, size and lastmodified.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            format: JWT
          required: true
      responses:
        '200':
          description: OK.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetAttachmentListResponse'
        '401':
          description: Invalid JWT.
          content:
            'application/json':
              schema:
                $ref: '../common-openapi.yml#/components/schemas/jsonApiError'
        '403':
          $ref: '../common-openapi.yml#/components/responses/missingApiKeyResponse'

    post:
      tags:
        - Attachments
      summary: Upload attachment.
      description: |
        This endpoint returns a signed url that a consumer can use to upload an attachment to the object storage.
        The signed url is valid for 5 minutes until it becomes invalid for further usage and in which a new
        signed url must be created. For every signed url created, a unique id is also created and returned in the
        response.

      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            format: JWT
          required: true
      responses:
        '200':
          description: OK.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UploadAttachmentResponse'
        '401':
          description: Invalid JWT.
          content:
            'application/json':
              schema:
                $ref: '../common-openapi.yml#/components/schemas/jsonApiError'
        '403':
          $ref: '../common-openapi.yml#/components/responses/missingApiKeyResponse'

  /users/me/attachments/{filename}:
    delete:
      tags:
        - Attachments
      summary: Deletes an attachment.
      description: |
        This endpoint deletes an attachment from the object storage.
      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            format: JWT
          required: true
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/DeleteAttachmentResponse'
        '401':
          description: Invalid JWT.
          content:
            'application/json':
              schema:
                $ref: '../common-openapi.yml#/components/schemas/jsonApiError'
        '403':
          $ref: '../common-openapi.yml#/components/responses/missingApiKeyResponse'

components:
  securitySchemes:
    $ref: '../common-openapi.yml#/components/securitySchemes'

  schemas:
    Address:
      type: object
      properties:
        city:
          type: string
        street:
          type: string
        postalCode:
          type: string

    User:
      type: object
      required:
        - personalNumber
        - firstName
        - lastName
      properties:
        personalNumber:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        civilStatus:
          type: string
        mobilePhone:
          type: string
        email:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        uuid:
          type: string
        createdAt:
          type: string

    GetUserResponse:
      type: object
      properties:
        jsonapi:
          type: object
          properties:
            version:
              type: string
              example: '1.0'
            data:
              type: object
              properties:
                type:
                  type: string
                attributes:
                  type: object
                  properties:
                    item:
                      $ref: '#/components/schemas/User'

    ListAttachment:
      type: object
      properties:
        Key:
          type: string
        Size:
          type: number
        LastModified:
          type: string

    GetAttachmentListResponse:
      type: object
      properties:
        jsonapi:
          type: object
          properties:
            version:
              type: string
              example: '1.0'
            data:
              type: object
              properties:
                type:
                  type: string
                attributes:
                  type: object
                  properties:
                    files:
                      type: array
                      items:
                        $ref: '#/components/schemas/ListAttachment'
                    totalFileSizeSumInBytes:
                      type: number

    UploadAttachmentResponse:
      type: object
      properties:
        jsonapi:
          type: object
          properties:
            version:
              type: string
              example: '1.0'
            data:
              type: object
              properties:
                id:
                  type: string
                uploadUrl:
                  type: string

    DeleteAttachmentResponse:
      type: object
      properties:
        jsonapi:
          type: object
          properties:
            version:
              type: string
              example: '1.0'
            data:
              type: object
              properties:
                type:
                  type: string
