service: users-api

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-apigw-binary
  - serverless-apigwy-binary

projectDir: ../../

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}
  apiGateway:
    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
    restApiResources:
      users:
        "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayResourceUsers

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
          # Restrict our IAM role permissions to the specific table for the stage
          Resource:
            - "Fn::ImportValue": ${self:custom.resourcesStage}-UsersTableArn

        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:ListObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - Fn::ImportValue: ${self:custom.resourcesStage}-AttachmentsBucketArn
            - Fn::Join:
                - ""
                - - Fn::ImportValue: ${self:custom.resourcesStage}-AttachmentsBucketArn
                  - "/*"
        - Effect: Allow
          Action:
            - kms:Decrypt
            - kms:DescribeKey
            - kms:Encrypt
            - kms:GenerateDataKey*
            - kms:ReEncrypt*
          Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*

functions:
  getUser:
    handler: lambdas/getUser.main
    events:
      - http:
          path: /users/{personalNumber}
          method: get
          cors: true
          private: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

  me:
    handler: lambdas/getUser.main
    events:
      - http:
          path: /users/me
          method: get
          cors: true
          private: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

  getAttachmentList:
    handler: lambdas/getAttachmentList.main
    environment:
      BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-AttachmentsBucketName
    events:
      - http:
          path: /users/me/attachments
          method: get
          cors: true
          private: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

  uploadAttachment:
    handler: lambdas/uploadAttachment.main
    environment:
      BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-AttachmentsBucketName
    events:
      - http:
          path: /users/me/attachments
          method: post
          cors: true
          private: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

  deleteAttachment:
    handler: lambdas/deleteAttachment.main
    environment:
      BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-AttachmentsBucketName
    events:
      - http:
          path: /users/me/attachments/{filename}
          method: delete
          cors: true
          private: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

  getAttachment:
    handler: lambdas/getAttachment.main
    environment:
      BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-AttachmentsBucketName
    events:
      - http:
          path: /users/me/attachments/{filename}
          method: get
          contentHandling: CONVERT_TO_BINARY
          cors: true
          private: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

           