service: helsingborg-io-sls-userdata-api

plugins:
  - serverless-bundle
  - serverless-offline

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  apiGateway:
    apiKeySourceType: HEADER
  apiKeys:
    - ${self:custom.stage}-hbg-userdata-apikey
  usagePlan:
    quota:
      limit: 10
      offset: 0
      period: DAY
    throttle:
      burstLimit: 10
      rateLimit: 10
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /forms
  # - method: POST request
  get:
    handler: get.main
    events:
      - http:
          path: api/v1/users
          method: get
          cors: true
          private: true
