openapi: '3.0.3'
info:
  title: Status
  description: Api for fetching api status messages.
  contact:
    name: GitHub Repo
    url: https://github.com/helsingborg-stad/helsingborg-io-sls-api
  version: '1.0'
  license:
    name: MIT
    url: 'https://github.com/helsingborg-stad/helsingborg-io-sls-api#license'
servers:
  - url: https://dev.api.helsingborg.io
  - url: https://release.api.helsingborg.io
  - url: https://api.helsingborg.io

paths:
  /status/messages:
    get:
      tags:
        - Status
      summary: Get API status messages.
      description: |
        This endpoint returns a list of messages that would be used and displayed by a consumer.
        The list of messages returned in the response could be on of the following:

        1. info
        2. warning
        3. maintenance

        in which the severity of the message is increased with start from position1.

      security:
        - ApiKeyAuth: []
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            format: JWT
          required: true
      responses:
        '200':
          description: OK.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetStatusResponse'
        '401':
          description: Invalid JWT.
          content:
            'application/json':
              schema:
                $ref: '../common-openapi.yml#/components/schemas/jsonApiError'
        '403':
          $ref: '../common-openapi.yml#/components/responses/missingApiKeyResponse'

components:
  securitySchemes:
    $ref: '../common-openapi.yml#/components/securitySchemes'

  schemas:
    Message:
      type: object
      properties:
        title:
          type: string
        text:
          type: string

    MessageItem:
      type: object
      properties:
        message:
          type: object
          $ref: '#/components/schemas/Message'
        type:
          type: string
          enum: [info, warning, maintenance]
        start:
          type: string
        expiry:
          type: string

    GetStatusResponse:
      type: object
      properties:
        jsonapi:
          type: object
          properties:
            version:
              type: string
              example: '1.0'
            data:
              type: object
              properties:
                attributes:
                  type: object
                  properties:
                    messages:
                      type: array
                      items:
                        $ref: '#/components/schemas/MessageItem'
