openapi: '3.0.3'
info:
  title: Version
  description: |
    Endpoint for querying Mitt Helsingborg app version info.
  contact:
    name: GitHub Repo
    url: https://github.com/helsingborg-stad/helsingborg-io-sls-api
  version: '1.0'
  license:
    name: MIT
    url: 'https://github.com/helsingborg-stad/helsingborg-io-sls-api/blob/master/LICENSE'
servers:
  - url: https://dev.api.helsingborg.io
  - url: https://release.api.helsingborg.io
  - url: https://api.helsingborg.io

paths:
  /version:
    get:
      tags:
        - Version
      summary: Check version status
      description: |
        Check if a newer version is available and if it is required.
        Uses the `User-Agent` header to determine request version.
      security:
        - ApiKeyAuth: []
      parameters:
        - name: User-Agent
          in: header
          schema:
            $ref: '../common-openapi.yml#/components/schemas/userAgentHeader'
      responses:
        '200':
          description: |
            OK. The `updateUrl` property will be appropriate for the platform
            indicated by the `User-Agent` header.
          content:
            'application/vnd.api+json':
              schema:
                $ref: '#/components/schemas/versionResult'
        '400':
          description: Invalid `User-Agent` header.
          content:
            'application/vnd.api+json':
              schema:
                $ref: '../common-openapi.yml#/components/schemas/jsonApiError'
        '403':
          $ref: '../common-openapi.yml#/components/responses/missingApiKeyResponse'

components:
  securitySchemes:
    $ref: '../common-openapi.yml#/components/securitySchemes'
  schemas:
    versionResult:
      properties:
        jsonapi:
          type: object
          properties:
            version:
              type: string
              example: '1.0'
        data:
          type: object
          properties:
            attributes:
              type: object
              properties:
                status:
                  type: string
                  enum:
                    - OK
                    - UPDATE_OPTIONAL
                    - UPDATE_REQUIRED
                  example: UPDATE_REQUIRED
                updateUrl:
                  type: string
                  example: https://link.to.apple.app.store/
