org: hbgworks
service: version-api

frameworkVersion: ^3.26.0

plugins:
  - serverless-bundle

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  versionFunctions: false
  tracing:
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  apiGateway:
    restApiId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
    restApiResources:
      version: !ImportValue ${self:custom.stage}-ExtApiGatewayResourceVersion

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - SSM:GetParameter*
          Resource:
            - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${file(../../config.json):${self:custom.stage}.version.envsKeyName}'

functions:
  get:
    handler: src/lambdas/getStatus.main
    events:
      - http:
          path: version
          method: get
          private: true
          cors: true
