components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API Key used to authenticate the endpoint.

  responses:
    missingApiKeyResponse:
      description: API Key was not provided or is invalid.
      content:
        'application/json':
          schema:
            type: object
            example:
              message: 'Missing Authentication Token'

  schemas:
    jsonApiError:
      properties:
        jsonapi:
          type: object
          properties:
            version:
              type: string
              example: '1.0'
        data:
          type: object
          properties:
            status:
              type: string
              example: '400'
            code:
              type: number
              example: 400
            title:
              type: string
              example: InvalidArgumentError
            detail:
              type: string
              example: Invalid argument X supplied to Y
            message:
              type: string
              example: Invalid argument X supplied to Y
            stack:
              type: string
              example: "InvalidArgumentError: Invalid argument X supplied to Y\n    at Object.transform"
