service: navet-ms

plugins:
  - serverless-bundle

projectDir: ../../

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  tracing:
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:getObject
          Resource:
            - "Fn::Join":
                - ""
                - - Fn::ImportValue: ${self:custom.stage}-CertificatesBucketArn
                  - "/*"

        - Effect: Allow
          Action:
            - SSM:GetParameter*
          Resource:
            - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${file(../../config.json):${self:custom.stage}.navet.envsKeyName}"

        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: "*"

        - Effect: Allow
          Action:
            - kms:Decrypt
            - kms:GenerateDataKey
          Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*

functions:
  poll:
    handler: lambdas/pollUser.main
    events:
      - eventBridge:
          pattern:
            source:
              - bankId.collect
