service: office-auth

plugins:
  - serverless-bundle
  - serverless-add-api-key

projectDir: ../../../

custom: ${file(../../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: ${self:custom.runtime}
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-north-1
  endpointType: regional
  tracing:
    lambda: true
  apiGateway:
    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
    restApiResources:
      auth:
        "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayResourceAuth

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  deploymentBucket:
    name: ${self:custom.deploymentBucket}

functions:
  officeAuthorizer:
    handler: lambdas/officeAuthorizer.main
    environment:
      executeResourceArns:
        !Join
            - ""
            - - "arn:aws:execute-api:${self:provider.region}:${aws:accountId}:"
              - Fn::ImportValue: ${self:custom.stage}-ExtApiGatewayRestApiId
              - /*/*/*/*

resources:
  Resources:
    OfficeAuthorizerPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt OfficeAuthorizerLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal:
          !Join ["", ["apigateway.", { Ref: "AWS::URLSuffix" }]]

    GatewayOfficeAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: ${self:custom.stage}-OfficeAuthorizer
        RestApiId: ${self:provider.apiGateway.restApiId}
        Type: TOKEN
        IdentitySource: method.request.header.Authorization
        AuthorizerUri:
          Fn::Join:
            - ""
            - - "arn:aws:apigateway:"
              - Ref: "AWS::Region"
              - ":lambda:path/2015-03-31/functions/"
              - Fn::GetAtt: "OfficeAuthorizerLambdaFunction.Arn"
              - "/invocations"

  Outputs:
    AuthorizerId:
      Value:
        Ref: GatewayOfficeAuthorizer
      Export:
        Name: ${self:custom.stage}-officeAuthorizerId
