openapi: '3.0.3'
info:
  title: Viva cases api
  description: Api dealing with Viva cases.
  contact:
    name: GitHub Repo
    url: https://github.com/helsingborg-stad/helsingborg-io-sls-api
  version: '1.0'
  license:
    name: MIT
    url: 'https://github.com/helsingborg-stad/helsingborg-io-sls-api#license'
servers:
  - url: https://dev.api.helsingborg.io
  - url: https://release.api.helsingborg.io
  - url: https://api.helsingborg.io

paths:
  /viva-cases/{caseId}/persons:
    put:
      tags:
        - Viva persons
      summary: Adds co-applicant to case.
      description: This endpoint adds a co-applicant to another applicants case.
      security:
        - ApiKeyAuth: []
        - AuthToken: []
      parameters:
        - name: caseId
          required: true
          in: path
          description: Case id to add co-applicant to.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../../../viva-case-common-openapi.yml#/components/schemas/Person'
      responses:
        '200':
          description: OK.
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/AddCasePersonResponse'
        '401':
          description: Invalid JWT.
          content:
            'application/json':
              schema:
                $ref: '../../../common-openapi.yml#/components/schemas/jsonApiError'
        '403':
          description: Missing Api Key or co-applicant not allowed to apply.
          content:
            'application/json':
              schema:
                oneOf:
                  - $ref: '../../../common-openapi.yml#/components/schemas/missingApiKeySchema'
                  - $ref: '#/components/schemas/UnAuthorizedCoApplicant'

components:
  securitySchemes:
    $ref: '../../../common-openapi.yml#/components/securitySchemes'

  schemas:
    UnAuthorizedCoApplicant:
      type: object
      example:
        message: 'Co-applicant not allowed to apply'
      properties:
        message:
          type: string

    AddCasePersonResponse:
      type: object
      properties:
        jsonapi:
          type: object
          properties:
            version:
              type: string
              example: '1.0'
            data:
              type: object
              properties:
                type:
                  type: string
                attributes:
                  type: object
                  properties:
                    caseItem:
                      $ref: '../../../viva-case-common-openapi.yml#/components/schemas/Case'
