version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "unsafe-perm=true" > .npmrc
      - echo "registry=https://registry.yarnpkg.com/" >> .npmrc
      - echo "@helsingborg-stad:registry=https://npm.pkg.github.com" >> .npmrc
      - echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
      - echo "always-auth=true" >> .npmrc
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - echo "Test alot!"

cache:
  paths:
    - node_modules/**/*
