service: viva-ms

plugins:
  - serverless-bundle

projectDir: ../../../

custom: ${file(../../../serverless.common.yml):custom}

package:
  individually: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  versionFunctions: false
  eventBridge:
    useCloudFormation: true
  tracing:
    apiGateway: false
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - SSM:GetParameter*
          Resource:
            - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${file(../../../config.json):${self:custom.stage}.vada.envsKeyName}'
            - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${file(../../../config.json):${self:custom.stage}.cases.providers.viva.envsKeyName}'
            - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${file(../../../config.json):${self:custom.stage}.vivaNewApplication.envsKeyName}'

        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: '*'

        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - Fn::ImportValue: ${self:custom.resourcesStage}-AttachmentsBucketArn
            - Fn::Join:
                - ''
                - - Fn::ImportValue: ${self:custom.resourcesStage}-AttachmentsBucketArn
                  - '/*'
            - Fn::ImportValue: ${self:custom.resourcesStage}-PdfStorageBucketArn
            - Fn::Join:
                - ''
                - - Fn::ImportValue: ${self:custom.resourcesStage}-PdfStorageBucketArn
                  - '/*'

        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:GetItem
          Resource:
            - 'Fn::ImportValue': ${self:custom.resourcesStage}-CasesTableArn

        - Effect: Allow
          Action:
            - dynamodb:Query
          Resource:
            - !ImportValue ${self:custom.resourcesStage}-CasesTableAllIndexArn

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
          Resource:
            - 'Fn::ImportValue': ${self:custom.resourcesStage}-UsersTableArn

        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
          Resource:
            - 'Fn::ImportValue': ${self:custom.resourcesStage}-FormsTableArn

        - Effect: Allow
          Action:
            - kms:Decrypt
            - kms:GenerateDataKey
          Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*

functions:
  applicationStatus:
    handler: src/lambdas/applicationStatus.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - usersMs.findUser
            detail-type:
              - usersMsFindUserSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn
      - eventBridge:
          pattern:
            source:
              - vivaMs.submitApplication
            detail-type:
              - applicationReceivedSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  personApplicationStatus:
    handler: src/lambdas/personApplicationStatus.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.applicationStatus
            detail-type:
              - applicationStatusSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  personApplication:
    handler: src/lambdas/personApplication.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.personApplicationStatus
            detail-type:
              - checkOpenPeriodSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  createNewVivaCase:
    handler: src/lambdas/createNewVivaCase.main
    reservedConcurrency: 1
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.personApplicationStatus
            detail-type:
              - checkOpenNewApplicationSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  createVivaCase:
    handler: src/lambdas/createVivaCase.main
    reservedConcurrency: 1
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.personApplication
            detail-type:
              - personDetailSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  submitApplication:
    handler: src/lambdas/submitApplication.main
    timeout: 30
    environment:
      BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-AttachmentsBucketName
    events:
      - sqs:
          arn: !ImportValue ${self:custom.stage}-VivaSubmissionQueueArn
          batchSize: 1

  syncCaseCompletions:
    handler: src/lambdas/syncCaseCompletions.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.applicationStatus
            detail-type:
              - applicationStatusSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  checkCompletionsStatus:
    handler: src/lambdas/checkCompletionsStatus.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.syncCaseCompletions
            detail-type:
              - syncSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  setCaseCompletions:
    handler: src/lambdas/setCaseCompletions.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.checkCompletionsStatus
            detail:
              caseStatusType: [{ 'anything-but': { 'prefix': 'active:ongoing' } }]
              caseState:
                [
                  { 'anything-but': 'VIVA_RANDOM_CHECK_RECEIVED' },
                  { 'anything-but': 'VIVA_COMPLETION_RECEIVED' },
                ]
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  checkCompletionsDueDate:
    handler: src/lambdas/checkCompletionsDueDate.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.checkCompletionsStatus
            detail-type:
              - 'Completions Due Date Probably Overdue'
            detail:
              caseStatusType: [{ 'anything-but': { 'prefix': 'active:processing' } }]
              caseState: [{ 'anything-but': 'VIVA_APPLICATION_RECEIVED' }]
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  submitCompletion:
    handler: src/lambdas/submitCompletion.main
    timeout: 30
    environment:
      BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-AttachmentsBucketName
    events:
      - eventBridge:
          pattern:
            source:
              - casesApi.updateCase
            detail-type:
              - casesApiUpdateCaseSuccess
            detail:
              status:
                type: [{ 'prefix': 'active:submitted' }]
              state: ['VIVA_RANDOM_CHECK_REQUIRED', 'VIVA_COMPLETION_REQUIRED']
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  syncOfficers:
    handler: src/lambdas/syncOfficers.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - cases.database
            detail-type:
              - INSERT
              - MODIFY
            detail:
              dynamodb:
                NewImage:
                  provider:
                    S: ['VIVA']
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  syncWorkflow:
    handler: src/lambdas/syncWorkflow.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - bankId.collect
            detail-type:
              - BankIdCollectComplete
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  decideCaseStatus:
    handler: src/lambdas/decideCaseStatus.main
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.syncWorkflow
            detail-type:
              - syncWorkflowSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  syncExpiryTime:
    handler: src/lambdas/syncExpiryTime.main
    events:
      - eventBridge:
          pattern:
            source:
              - casesApi.updateCase
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn
      - eventBridge:
          pattern:
            source:
              - vivaMs.decideCaseStatus
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn
      - eventBridge:
          pattern:
            source:
              - vivaMs.setCaseCompletions
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  syncNewCaseWorkflowId:
    handler: src/lambdas/syncNewCaseWorkflowId.main
    timeout: 30
    events:
      - eventBridge:
          pattern:
            source:
              - vivaMs.applicationStatus
            detail-type:
              - applicationStatusSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  generateRecurringCaseHtml:
    handler: src/lambdas/generateRecurringCaseHtml.main
    environment:
      PDF_STORAGE_BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-PdfStorageBucketName
    events:
      - eventBridge:
          pattern:
            source:
              - casesApi.updateCase
            detail-type:
              - casesApiUpdateCaseSuccess
            detail:
              status:
                type: [{ 'prefix': 'active:submitted' }]
              state: ['VIVA_CASE_CREATED']
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn

  copyAttachment:
    handler: src/lambdas/copyAttachment.main
    environment:
      BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-AttachmentsBucketName
    events:
      - eventBridge:
          pattern:
            source:
              - 'aws.s3'
            detail-type:
              - 'Object Created'
            detail:
              bucket:
                name:
                  - !ImportValue ${self:custom.resourcesStage}-AttachmentsBucketName
              reason:
                - 'PutObject'
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn
