service: cases-api

plugins:
  - serverless-bundle
  - serverless-offline

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  apiGateway:
    restApiId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId:
      "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
    restApiResources:
      cases:
        "Fn::ImportValue": ${self:custom.stage}-ExtApiGatewayResourceCases

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      # Restrict our IAM role permissions to the specific table for the stage
      Resource:
        - "Fn::ImportValue": ${self:custom.resourcesStage}-CasesTableArn

    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        - "Fn::ImportValue": ${self:custom.resourcesStage}-FormsTableArn

functions:
  getCase:
    handler: lambdas/getCase.main
    events:
      - http:
          path: /cases/{id}
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

  getCaseList:
    handler: lambdas/getCaseList.main
    events:
      - http:
          path: /cases
          method: get
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

  createCase:
    handler: lambdas/createCase.main
    events:
      - http:
          path: /cases
          method: post
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

  updateCase:
    handler: lambdas/updateCase.main
    events:
      - http:
          path: /cases/{id}
          method: put
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId

  deleteCase:
    handler: lambdas/deleteCase.main
    events:
      - http:
          path: /cases/{id}
          method: delete
          cors: true
          authorizer:
            type: CUSTOM
            authorizerId: !ImportValue ${self:custom.stage}-authorizerId
