openapi: '3.0.3'
info:
  title: Metrics
  description: API for fetching current metrics.
  contact:
    name: GitHub Repo
    url: https://github.com/helsingborg-stad/helsingborg-io-sls-api
  version: '1.0'
  license:
    name: MIT
    url: 'https://github.com/helsingborg-stad/helsingborg-io-sls-api/blob/master/LICENSE'
servers:
  - url: https://dev.api.helsingborg.io
  - url: https://release.api.helsingborg.io
  - url: https://api.helsingborg.io

paths:
  /metrics/ekb:
    get:
      tags:
        - Metrics
      summary: Get metrics related to EKB
      description: Returns EKB-related metrics in a given format.
      security:
        - ApiKeyAuth: []
      parameters:
        - name: format
          required: true
          in: query
          description: Format to return metrics in.
          schema:
            type: string
            enum:
              - ebnf
      responses:
        '200':
          description: OK.
          content:
            text/plain:
              schema:
                type: string
                example: |
                  # HELP ekb_cases_total The total amount of cases.
                  # TYPE ekb_cases_total gauge
                  ekb_cases_total{status="active"} 50
                  ekb_cases_total{status="closed"} 232
        '400':
          description: Invalid format specified.
          content:
            'application/vnd.api+json':
              schema:
                $ref: '../common-openapi.yml#/components/schemas/jsonApiError'
        '403':
          description: API Key was not provided or is invalid.
          content:
            'application/json':
              schema:
                type: object
                example:
                  message: 'Missing Authentication Token'

components:
  securitySchemes:
    $ref: '../common-openapi.yml#/components/securitySchemes'
