service: metrics-api

plugins:
  - serverless-bundle
  - serverless-add-api-key

projectDir: ../../

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  versionFunctions: false
  tracing:
    lambda: true
  apiGateway:
    restApiId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
    restApiResources:
      metrics: !ImportValue ${self:custom.stage}-ExtApiGatewayResourceMetrics

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
          Resource:
            - !ImportValue ${self:custom.resourcesStage}-CasesTableAllIndexArn

        - Effect: Allow
          Action:
            - kms:Decrypt
            - kms:GenerateDataKey
          Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*

functions:
  get:
    handler: src/lambdas/get.main
    events:
      - http:
          path: metrics/ekb
          method: get
          private: true
          cors: true
