org: hbgworks
service: cases-ms

frameworkVersion: ^3.26.0

plugins:
  - serverless-bundle

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-north-1
  endpointType: regional
  versionFunctions: false
  tracing:
    apiGateway: false
    lambda: true

  environment:
    stage: ${self:custom.stage}
    resourcesStage: ${self:custom.resourcesStage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:UpdateItem
          Resource:
            - !ImportValue ${self:custom.resourcesStage}-CasesTableArn
            - !ImportValue ${self:custom.resourcesStage}-CasesTableAllIndexArn

        - Effect: Allow
          Action:
            - kms:Decrypt
          Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*

        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - Fn::ImportValue: ${self:custom.resourcesStage}-PdfStorageBucketArn
            - Fn::Join:
                - ''
                - - Fn::ImportValue: ${self:custom.resourcesStage}-PdfStorageBucketArn
                  - '/*'

functions:
  updatePdf:
    handler: src/lambdas/updatePdf.main
    environment:
      PDF_STORAGE_BUCKET_NAME: !ImportValue ${self:custom.resourcesStage}-PdfStorageBucketName
    events:
      - eventBridge:
          pattern:
            source:
              - pdfMs.generate
            detail-type:
              - PdfMsGenerateSuccess
          retryPolicy:
            maximumEventAge: 3600
            maximumRetryAttempts: 3
          deadLetterQueueArn: !ImportValue ${self:custom.resourcesStage}-EventBridgeDeadLetterQueueArn
